import json
import boto3
import os
import re
import time
import urllib.request
from datetime import datetime, timezone
from botocore.exceptions import ClientError
from botocore.config import Config
from decimal import Decimal

# --- CONFIGURATION ---
INTENT_MODEL = "us.amazon.nova-lite-v1:0"
LIGHT_MODEL = "us.amazon.nova-lite-v1:0"
DYNAMODB_TABLE_NAME = "TraceAbilityLogs"

bedrock_client = boto3.client("bedrock-runtime", region_name="us-east-1", config=Config(retries={"max_attempts": 2})) 
dynamodb = boto3.resource("dynamodb", region_name="ap-south-1")
table = dynamodb.Table(DYNAMODB_TABLE_NAME)

# --- UTILS ---
class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal): return float(obj)
        return super(DecimalEncoder, self).default(obj)

def post_github_comment(commit_id, analysis, story):
    """Posts analysis to GitHub using built-in urllib (No Layers Required)."""
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")
    if not token or not repo or "local-" in str(commit_id): return

    url = f"https://api.github.com/repos/{repo}/commits/{commit_id}/comments"
    comment_body = (
        f"### 🚀 Trace-Ability AI Analysis\n\n"
        f"**Summary:** {analysis.get('summary')}\n"
        f"**Category:** `{analysis.get('category')}` | **Trust Score:** {analysis.get('final_trust_score')}%\n\n"
        f"#### 🛡️ Architecture Narrative\n{story}\n\n"
        f"---\n*Generated by Trace-Ability Engine*"
    )
    
    data = json.dumps({"body": comment_body}).encode("utf-8")
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Authorization", f"token {token}")
    req.add_header("Accept", "application/vnd.github.v3+json")
    req.add_header("Content-Type", "application/json")
    req.add_header("User-Agent", "TraceAbility-App")

    try:
        with urllib.request.urlopen(req) as f:
            print(f"GitHub Comment Posted: {f.status}")
    except Exception as e:
        print(f"GitHub API Error: {e}")

# --- AI CORE ---
def invoke_nova(model_id, system_prompt, user_prompt, max_tokens):
    payload = {
        "schemaVersion": "messages-v1",
        "messages": [{"role": "user", "content": [{"text": f"{system_prompt}\n\nInput: {user_prompt}"}]}],
        "inferenceConfig": {"max_new_tokens": max_tokens, "temperature": 0.1}
    }
    try:
        response = bedrock_client.invoke_model(modelId=model_id, body=json.dumps(payload), contentType="application/json")
        response_body = json.loads(response["body"].read())
        return response_body["output"]["message"]["content"][0]["text"]
    except Exception as e:
        print(f"Bedrock Error: {e}"); raise

def invoke_intent_analysis(diff_content):
    output = invoke_nova(INTENT_MODEL, "Return STRICT JSON: summary, intent_analysis, category, risk_score(0-100), confidence_score(0-100), spec_alignment_score(0-100).", diff_content, 500)
    match = re.search(r'\{.*\}', output, re.DOTALL)
    return json.loads(match.group(0)) if match else {"summary": "Analysis failed", "category": "Other"}

def calculate_trust_score(data):
    conf = data.get("confidence_score", 50)
    align = data.get("spec_alignment_score", 50)
    trust = ((conf ** 0.5) * 0.5 + (align ** 0.5) * 0.5) * 10
    return Decimal(str(round(trust, 2)))

# --- HANDLER ---
def lambda_handler(event, context):
    # CORS Headers
    headers = {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type"
    }

    if event.get("requestContext", {}).get("http", {}).get("method") == "OPTIONS":
        return {"statusCode": 200, "headers": headers}

    try:
        method = event.get("requestContext", {}).get("http", {}).get("method", "POST")
        
        # 1. GET LOGS
        if method == "GET":
            items = table.scan(Limit=15).get('Items', [])
            items.sort(key=lambda x: x.get('logged_at', ''), reverse=True)
            return {"statusCode": 200, "headers": headers, "body": json.dumps(items, cls=DecimalEncoder)}

        # 2. PROCESS COMMIT
        body = event if "commit_id" in event else json.loads(event.get("body", "{}"))
        commit_id, diff = body.get("commit_id"), body.get("diff")

        if not commit_id or not diff:
            return {"statusCode": 400, "headers": headers, "body": json.dumps({"error": "Missing data"})}

        # AI Sequence
        intent_result = invoke_intent_analysis(diff)
        intent_result["final_trust_score"] = calculate_trust_score(intent_result)
        arch_story = invoke_nova(LIGHT_MODEL, "Summarize why this change matters for business/maintainability in 3 sentences.", diff, 200)

        # Database Store
        table.put_item(Item={
            "commit_id": commit_id,
            "summary": intent_result.get("summary"),
            "intent_analysis": intent_result.get("intent_analysis"),
            "category": intent_result.get("category"),
            "trust_score": intent_result["final_trust_score"],
            "risk_score": Decimal(str(intent_result.get("risk_score", 50))),
            "architecture_story": arch_story,
            "logged_at": datetime.now(timezone.utc).isoformat(),
            "expire_at": int(time.time()) + (30 * 86400)
        })

        # GitHub Comment
        post_github_comment(commit_id, intent_result, arch_story)

        return {
            "statusCode": 200,
            "headers": headers,
            "body": json.dumps({"status": "success", "analysis": intent_result, "story": arch_story}, cls=DecimalEncoder)
        }

    except Exception as e:
        print(f"Error: {e}")
        return {"statusCode": 500, "headers": headers, "body": json.dumps({"error": str(e)})}